from typing import List, Tuple, Union
from biosequence.sequence import Sequence

def read_fasta(filename:str) -> Tuple[List[str], List[str]]:    ...
def printAlign(sequence1: Union[str, Sequence], 
               sequence2:Union[str, Sequence],
               spacing:int, 
               line_width:int, 
               show_sequence:bool) -> None:    ...
def setAlignPara(match:int, mismatch:int, 
                 gap_open:int, gap_extend:int) -> None:    ...
def setStartCoden(coden:Union[str, List[str]]) -> None: ...
